Major build system reorganization
I reorganized all the code in differente directories based on the
exact purpose of each thing (kernel, agent, control, etc).

Now there is a top-level Makefile that will call an individual
Makefile for each directory. This is more modular and the whole
repo is better organized.

Besides that, now everything can be compiled from inside the Docker
container by using the 'build.sh' script.
Ex:
  Compile everything:
    cd src/
    ./build.sh

  Compile only BPF objects:
    cd src/
    ./build.sh kernel

There were also some fixes to guarantee that calls the container
has ownership over the generated files so it can just run
'make clean' without permission errors. But even if that happens,
it will suffice to run './build.sh clean'.

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -1,103 +1,35 @@
-TARGETS = sfc_stages_kern
-TARGETS += sfc_classifier_kern
-TARGETS += sfc_agent_user
-TARGETS += map_inspector_user
-# TARGETS += ../test/tc_redirect/tc_bench01_redirect_kern
-#TARGETS += ../test/tc_redirect/tc_bench01_redirect_user
+# === Variables ===
 
-# Generate file name-scheme based on TARGETS
-KERN = $(filter %_kern, $(TARGETS))
-KERN_SOURCES = ${KERN:=.c}
-KERN_OBJECTS = ${KERN_SOURCES:.c=.o}
-
-USR = $(filter %_user, $(TARGETS))
-USER_OBJECTS = ${USR}
-
-LLC ?= llc
-CLANG ?= clang
-CC ?= gcc
-
-# Add utils
-UTILSDIR = utils
-UTILS_SRC = ${wildcard ${UTILSDIR}/*.c}
-UTILS = ${UTILS_SRC:.c=.o}
-
-# Build dir
+# Directory definitions
+UTILS_DIR = ./utils
 BUILD_DIR = ./build
+LIBBPF_DIR = libbpf/src
 
-# Add libbpf
-LIBBPF_DIR = ./libbpf/src
-OBJECT_LIBBPF = $(LIBBPF_DIR)/libbpf.a
+# === Targets ===
+all: build-dir kernel utils libbpf control agent chown
 
-CFLAGS += -I$(LIBBPF_DIR)/root/usr/include/
-CFLAGS += -Iheaders/ -Iutils/
-LDFLAGS ?= -L$(LIBBPF_DIR)
+.PHONY: all agent chown clean control libbpf kernel kdir-check utils
 
-BPFTMPDIR=/sys/fs/bpf/tmp
-JITEDOUTDIR=jited-output
-
-LIBS = -lbpf -lelf
-
-# Add libs from kernel source. This is needed since
-# we might use features not available on the standard
-# headers present on the current kernel. This is an attempt
-# to avoid installing updated headers system wide.
-# 
-# KDIR is checked by kdir-check target, and should be provided
-# when calling `make`.
-# 	ex: make ~/devel/kernels/linux-5.1
-CFLAGS += -I$(KDIR)/usr/include
-
-all: llvm-check kdir-check build-dir $(KERN_OBJECTS) $(USER_OBJECTS) utils
-
-.PHONY: clean $(CLANG) $(LLC) all utils debug jited-out
-
-debug: CFLAGS += -DDEBUG
-debug: all
+agent: build-dir libbpf utils
+	make -C agent
 
 build-dir:
-	mkdir -p ${BUILD_DIR}
-
-jited-out:
-	# TODO: Add statement to check if it is root
-	sudo mkdir -p ${BPFTMPDIR}
-	mkdir -p ${JITEDOUTDIR};
-	CFLAGS="-DBPFMAPDEF" $(MAKE) ${KERN_OBJECTS}
-	@for prog in ${KERN} ; do \
-		sudo bpftool prog loadall $${prog}.o ${BPFTMPDIR}; \
-	done
-	@for loaded in $$(sudo ls ${BPFTMPDIR}) ; do \
-		sudo bpftool prog dump jited pinned ${BPFTMPDIR}/$${loaded} linum > ${JITEDOUTDIR}/$${loaded}.jout; \
-	done
-	sudo chown -R ${USER} ${JITEDOUTDIR}
-	sudo rm -rdf ${KERN_OBJECTS} ${BPFTMPDIR}
+	mkdir -p $(BUILD_DIR)
 
 clean:
-	cd $(LIBBPF_DIR) && $(MAKE) clean;
-	cd $(UTILSDIR) && $(MAKE) clean;
-	rm -rdf ${BUILD_DIR}
-	rm -rdf ${JITEDOUTDIR}
+	cd libbpf/src && $(MAKE) clean;
+	cd utils && $(MAKE) clean;
+	rm -rdf $(BUILD_DIR)
 
-llvm-check: $(CLANG) $(LLC)
-	@for TOOL in $^ ; do \
-		if [ ! $$(command -v $${TOOL} 2>/dev/null) ]; then \
-			echo "*** ERROR: Cannot find tool $${TOOL}" ;\
-			exit 1; \
-		else true; fi; \
-	done
-
-kdir-check:
-	@if [ -z $(KDIR) ]; then \
-		echo "Error: KDIR is not set. Check README for more info"; \
-		exit 1; \
-	fi
-	@if [ ! -d $(KDIR)/include ]; then \
-		echo "Error: Directory $(KDIR)/include doesn't exist."; \
-		echo "Maybe run 'make kernel_headers' from $(KDIR)?"; \
-		exit 1; \
+chown:
+	@if [ -n $(OWNER) ]; then \
+		chown -R $(OWNER) libbpf/ build/; \
 	fi
 
-$(OBJECT_LIBBPF):
+control: build-dir
+	make -C control
+
+libbpf:
 	@if [ ! -d $(LIBBPF_DIR) ]; then \
 		echo "Error: Need libbpf submodule"; \
 		echo "May need to run git submodule update --init"; \
@@ -106,16 +38,18 @@ $(OBJECT_LIBBPF):
 		cd $(LIBBPF_DIR) && mkdir -p root; BUILD_STATIC_ONLY=y DESTDIR=root $(MAKE) install; \
 	fi
 
-$(KERN_OBJECTS): %.o: %.c
-	($(CLANG) -O2 -g -Wall $(CFLAGS) -target bpf -emit-llvm \
-		-c $< -o - || echo "clang failed") | \
-	$(LLC) -march=bpf -mcpu=probe  -filetype=obj -o $@
-	#pahole -J $@
-	@mv $@ ${BUILD_DIR}
+# We need acces to kernel headers. Pass it as KDIR:
+# 	ex: make KDIR=~/devel/kernels/linux-5.1
+# The Makefile under 'kernel/' will look for the headers under
+# this dir.
+kdir-check:
+	@if [ -z $(KDIR) ]; then \
+		echo "Error: KDIR is not set. Check README for more info"; \
+		exit 1; \
+	fi
 
-utils:
-	$(MAKE) -C $(UTILSDIR)
+kernel: build-dir kdir-check
+	$(MAKE) -C kernel KDIR=$(KDIR)
 
-$(USER_OBJECTS): %: %.c $(OBJECT_LIBBPF) utils Makefile
-	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $< $(UTILS) $(LIBS)
-	@mv $@ ${BUILD_DIR}
+utils: build-dir
+	$(MAKE) -C $(UTILS_DIR)
